### ISSUE TITLE
Create a colony-starter-angular package

### ISSUE THREAD

**Issue by ryanchristo** [JoinColony/colonyStarter#55]
## Description

Create a `colony-starter-angular` package that will demonstrate how to use colonyJS with Angular.

**Comment by fuguefoundation** [comment]
Hope to help move forward with this over the coming weeks.

**Comment by ryanchristo** [comment]
@fuguefoundation That would be great! Looking forward to getting this one started.

**Comment by fuguefoundation** [comment]
https://github.com/fuguefoundation/colony-starter-angular

@ryanchristo I took your suggestion and implemented `colonyNetwork` as a submodule. Definitely the right call, and it was a good learning experience for me. This also allowed me to avoid having conflicting package.lock and yarn.lock files. So it is working and implements `connectNetwork`, `createToken`, `createColony`, `getColonyClient`, `addDomain`, and `createTask` in the console.

However, I am still getting the same three errors you took a look at before and I've consolidated them into a single [issue](https://github.com/fuguefoundation/colony-starter-angular/issues/1) in this new repo. Basically, just comment out those three lines in the node_module files and it works. Two of the errors seem to be related to the initialization of `networkClient`, while the third one is for the initialization of `ecp`. I can only assume there is some relation to the version of the `colonyNetwork` submodule being checked out. As per [`initialize_project.sh`](https://github.com/JoinColony/colonyStarter/blob/master/packages/colony-starter-basic/scripts/initialize_project.sh) in colony-starter-basic, I am currently using commit [d50abbeb9f119850cb70e9ec854576123a707205](https://github.com/JoinColony/colonyNetwork/commits/d50abbeb9f119850cb70e9ec854576123a707205).

Hope you and your team have the chance to take a look. If you have any guidance on next steps for packaging or otherwise, please let me know. Cheers!

**Comment by ryanchristo** [comment]
@fuguefoundation This is great! Do you want to create a pull request in this repository and add it to the `packages` folder? We can work together on the errors and then get an initial beta version published!

Check out [Contributing](https://github.com/JoinColony/colonyStarter/blob/master/.github/CONTRIBUTING.md) for more information about opening a pull request.

**Comment by ryanchristo** [comment]
@fuguefoundation Do you need any help opening a pull request?

**Comment by fuguefoundation** [comment]
Hey @ryanchristo, my best coding time is on the weekends :) [PR submitted](https://github.com/JoinColony/colonyStarter/pull/58), thanks for the contributing guidance.

**Comment by ryanchristo** [comment]
As mentioned in colonyStarter#58, let's add some UI components in a new PR. Thanks again for the PR and laying the groundwork for `colony-starter-angular` package!
