### ISSUE TITLE
Explain networkClient contract address (Rinkeby)

### ISSUE THREAD

**Issue by fuguefoundation** [JoinColony/colonyStarter#71]
## Description

```
const { getNetworkClient } = require('@colony/colony-js-client');
const networkClient = await getNetworkClient('rinkeby', wallet);
```

`networkClient._contract.address` resolves to contract `0xE9d22C1cD375AF95f65201d7ed86e7AAf5aEDAEf` on Rinkeby. 

https://rinkeby.etherscan.io/address/0xE9d22C1cD375AF95f65201d7ed86e7AAf5aEDAEf

Having read through the docs/white paper, the following two things are still not clear to me and I would appreciate any insight, thanks!

1. Which specific Colony contract does this address refer to? Is it EtherRouter.sol or ColonyNetwork.sol or something else? Is using this address as a network client essentially the bridge to the "Common Colony" when working outside of local development?
2. Where in the colonyNetwork code is it designating this specific address as part of the `networkClient` instance that is returned?

Happy to explain further if my questions are not clear, still trying to connect the dots and move beyond local development to test net, while at the same time not reinventing the wheel.

**Comment by ryanchristo** [comment]
`0xE9d22C1cD375AF95f65201d7ed86e7AAf5aEDAEf` is the address of the `EtherRouter` contract.

This is a bit complex. More information about the EtherRouter can be found [here](https://docs.colony.io/colonynetwork/docs-upgrades-to-the-colony-network/#etherrouter). The `networkClient` connects to the `ColonyNetwork` contract via the `EtherRouter` contract, which allows us to upgrade contracts (deploy new contracts and reroute to those new contracts).

The "Common Colony" is now referred to as the "Meta Colony". The whitepaper needs to be updated. Using the `EtherRouter` contract is essentially a bridge to all colonyNetwork contracts whether they have been deployed to a local test network, `rinkeby` or `mainnet`.

There are no addresses specified in the colonyNetwork code because there is no way of determining what any of the addresses will be before the contracts are deployed. This `EtherRouter` address that is mentioned in this issue applies to the `rinkeby-v3` deployment and is specified  [here](https://github.com/JoinColony/colonyJS/blob/d6b1534baeb4892dd9e11103a6e641b62e7379b8/packages/colony-js-contract-loader-network/contracts/versioned/rinkeby-v3/EtherRouter.json#L124) within the colonyJS package `colony-js-contract-loader-network`.

**Comment by ryanchristo** [comment]
Also, if you want to see how this is implemented in colonyJS, you can see [here](https://github.com/JoinColony/colonyJS/blob/d6b1534baeb4892dd9e11103a6e641b62e7379b8/packages/colony-js-client/src/ColonyNetworkClient/index.js#L670) that the default query for the `networkClient` is targeting the `IColonyNetwork` interface contract using `EtherRouter`.

**Comment by ryanchristo** [comment]
[Here's another resource](https://www.youtube.com/watch?v=Sw9O2LWgWC0) if you want to learn more about "wiring upgradeable contracts". This is a talk one of our core developers gave at TruffleCon last Fall about this very topic.
